name: Run tests
on: [push]

jobs:
  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
    - name: Install composer dependencies
      run: composer install -n --prefer-dist
    - name: Prepare Laravel Application
      run: |
        cp.env.ci.env
        php artisan key:generate
    - name: Run tests
      run: php artisan test
